name: Cleanup

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Execute Atlas Pipeline]
    types: [completed]

permissions:
  actions: write
  contents: write

jobs:
  cleanup-old-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Atlas Pipeline via composite action
        uses: Netcracker/qubership-pipelines-declarative-executor/actions/cleanup_old_runs@main
        with:
          # GENERATED_BRANCHES_POOL_SIZE: ${{ vars.GENERATED_BRANCHES_POOL_SIZE }}
          ACCESS_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
