name: Execute Atlas Pipeline

run-name: Execute Atlas Pipeline - ${{ inputs.RUN_NAME }}

on:
  workflow_dispatch:
    inputs:
      PIPELINE_DATA:
        default: ''
        required: true
        type: string
      PIPELINE_VARS:
        default: ''
        required: false
        type: string
      DRY_RUN:
        default: false
        required: false
        type: boolean
      RUN_NAME:
        default: ':white_check_mark:'
        required: false
        type: string
      workflow_run_uuid:
        default: ''
        required: false
        type: string

permissions:
  actions: write
  contents: write

jobs:
  generate-and-execute-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: Netcracker/qubership-workflow-hub/actions/store-input-params@main
        with:
          input: ${{ toJSON(inputs) }}

      - name: Execute Atlas Pipeline via composite action
        uses: Netcracker/qubership-pipelines-declarative-executor/actions/execute_atlas_pipeline@main
        with:
          PIPELINE_DATA: ${{ inputs.PIPELINE_DATA }}
          PIPELINE_VARS: ${{ inputs.PIPELINE_VARS }}
          DRY_RUN: ${{ inputs.DRY_RUN }}
          ACCESS_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          EXECUTOR_REF: main
