# Needs to exist on default branch to be executable on our dynamically created ones (sub-workflows) where we override its contents
name: GENERATED_WORKFLOW

on:
  workflow_dispatch:

jobs:
  job:
    name: Generate Workflow Placeholder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4